name: Calc Unittesting
on:
  push:
    branches:
      - main
jobs:
  unittesting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        run: sudo apt update && sudo apt install -y python3
      - run: echo "python has been installed"

      - name: Unittesting Calc
        run: python Calc_Unittest.py
