name: Play Hello.py on push
on:
  push:
    branches:
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
      steps:
      - name: Install python
        run: sudo apt update && sudo apt install -y python3
        run: echo "python has been installed"

      - name: PlayScript
        run: python Hello.py

